service: bakery 

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-2
  environment:
    STATUS_CAKE_API_KEY: 'yourstatuscakekey'
    STATUS_CAKE_USER: 'yourstatuscakeusername'

functions:
  post:
    handler: handler.createOrUpdate
    events:
      - http: POST statuscheck

resources: 
  Resources:
    bakeryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bakery
        AttributeDefinitions:
          - AttributeName: StackName
            AttributeType: S
          - AttributeName: Endpoint
            AttributeType: S
        KeySchema:
          - AttributeName: StackName
            KeyType: HASH
          - AttributeName: Endpoint
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: bakeryTable
      Properties:
        PolicyName: bakery-lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: arn:aws:dynamodb:*:*:table/bakery
        Roles:
          - Ref: IamRoleLambdaExecution

